[package]
name = "default"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
azure_identity = "0.28.0"
azure_security_keyvault_secrets = "0.7.0"
setup.path = "../setup"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
