[package]
name = "default"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
azure_identity = "0.27.0"
azure_security_keyvault_secrets = "0.6.0"
dotazure = "0.2.0"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
